version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gigmedia_laravel_app
    container_name: gigmedia_laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - gigmedia_laravel

  web:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - gigmedia_laravel

  db:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: gigmedia_laravel
      MYSQL_ROOT_PASSWORD: RA~DWjHA!opnfM4 
      MYSQL_USER: gigmedia_laravel
      MYSQL_PASSWORD: eFZWi*SgX{goAru
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - gigmedia_laravel

networks:
  gigmedia_laravel:

volumes:
  mysql-data:
